### PR TITLE
Fix the warning page in NUC

### PR DESCRIPTION
**Pull request by tanminger**

### CODE REVIEW

**Comment by android-ia-srv** [comment]
Commit message is verified for commit id: https://github.com/android-ia/hardware-intel-kernelflinger/pull/7/commits/18e5428bf1211a583ebfdff6fc39140ecd2716fd <br>

**Comment by android-ia-srv** [comment]
Commit message is verified for commit id: https://github.com/android-ia/hardware-intel-kernelflinger/pull/7/commits/8b6a6432ccfcfdfdfece02f4c96d9be3563e35e3 <br>

**Comment by tanminger** [comment]
According the testing of Vedamurthy, Guruprasad, after cherry-pick this patch, the warning page in NUC is disappeared.

**Comment by sgnanase** [comment]
Merged...

**Pull request merged**
